import { AltUri } from "@ndn/naming-convention2";
import { pack } from "d3";
import { el, h } from "redom";

import { TimeSeries } from "./timeseries.js"; // eslint-disable-line no-unused-vars
import { Tree } from "./tree.js"; // eslint-disable-line no-unused-vars

export class Plots {
  constructor() {
    <div this="el" class="pure-g">
      <div class="pure-u-1">
        <h3 style="text-align:center">Time Range</h3>
        <input this="$timeRangePicker" id="timeRangePicker" style="width:100%; text-align:center;"/>
      </div>
      <div class="pure-u-1-2">
        <h3 style="text-align:center">Packet Throughput</h3>
        <TimeSeries this="$timeseries"/>
      </div>
      <div class="pure-u-1-2">
        <h3 style="text-align:center">Recent Packets</h3>
        <p style="text-align:center"><i><b>(I): Interest packet; (D): Data packet</b></i></p>
        <pre this="$recents" style="text-align:center">recent packets</pre>
      </div>
      <div class="pure-u-1" style="margin-top:50px;">
        <h3 style="text-align:center">Namespace Tree</h3>
        <Tree this="$tree"/>
        <p><b>Legend</b>
        <ul>
          <li><span style="background-color:rgba(240,232,120,0.97)">Yellow node
           without border:</span> Name of the interest that is not satisfied</li>
          <li><span style="background-color:rgba(240,232,120,0.97); border-style: solid;
          border-color:rgb(242, 150, 150);">Yellow node with border:</span>
            Name of the interest that has been satisfied. The border color denotes which key signs the data packet.</li>
          <li><span style="background-color:#8DB2FC">Blue node:</span> Name of the key.
             The node has the same border color as that of the packets it signs.</li>

        </ul>
        </p>
      </div>
      <div class="pure-u-1" style="margin-top:50px;text-align:center">
        <button this="$stop" class="pure-button pure-button-primary">Stop</button>
        <button this="$exit" class="pure-button pure-button-primary" disabled>Exit</button>
      </div>
    </div>;

    this.timeFilterStart = moment().startOf('hour').subtract(50, 'day');
    this.timeFilterEnd = moment().startOf('hour').add(50, 'day');
    this.recents = [];
    this.stopped = true;
    this.$stop.addEventListener("click", (evt) => {
      evt.preventDefault();
      this.stop();
      this.$stop.disabled = true;
      this.$exit.disabled = false;
    });
    this.$exit.addEventListener("click", (evt) => {
      evt.preventDefault();
      this.exit?.();
    });
  }

  update({ stream, prefixlen, suffixlen, exit }) {
    this.stop();
    this.addTimeRangePicker();
    this.stream = stream;
    this.$timeseries.updateTimeRange(this.timeFilterStart, this.timeFilterEnd);
    this.$tree.updateTimeRange(this.timeFilterStart, this.timeFilterEnd);
    this.$tree.update({ prefixlen, suffixlen });
    this.stream?.on("packet", (packet) => this.push(packet));
    this.exit = exit;
  }

  stop() {
    this.stream?.close();
  }

  // update the tree and the time series graph
  push(packet) {
    this.$timeseries.push(packet);
    this.$tree.push(packet);
    // the KEY type packet is generated by the program itself to draw graph
    if(packet.type == "K")
      return;
    this.recents.push("(" + packet.type + ") " + AltUri.ofName(packet.name));
    while (this.recents.length > 25) {
      this.recents.shift();
    }
    this.$recents.textContent = this.recents.join("\n");
  }

  addTimeRangePicker() {
    var self = this;
    $('#timeRangePicker').daterangepicker({
      opens: 'center',
      timePicker: true,
      startDate: this.timeFilterStart,
      endDate: this.timeFilterEnd,
      locale: {
        format: 'M/DD hh:mm A'
      }
    }, function(start, end, label) {
      self.timeFilterStart = start.toDate();
      self.timeFilterEnd = end.toDate();
      self.$timeseries.updateTimeRange(self.timeFilterStart, self.timeFilterEnd);
      self.$tree.updateTimeRange(self.timeFilterStart, self.timeFilterEnd);
      console.log("A new date selection was made: "
                  + self.timeFilterStart
                  + ' to ' + self.timeFilterEnd);
    });
  }

}
